<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11927" started-at="2016-05-19T06:36:51Z" finished-at="2016-05-19T06:37:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11927" started-at="2016-05-19T06:36:51Z" finished-at="2016-05-19T06:37:03Z">
      <class name="wealthsenseSiteTest.PrivateSiteTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:wealthsenseSiteTest.PrivateSiteTest@77caeb3e]" name="beforeTest" is-config="true" duration-ms="10108" started-at="2016-05-19T16:36:51Z" finished-at="2016-05-19T16:37:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="privateSiteTest()[pri:0, instance:wealthsenseSiteTest.PrivateSiteTest@77caeb3e]" name="privateSiteTest" duration-ms="1043" started-at="2016-05-19T16:37:01Z" finished-at="2016-05-19T16:37:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- privateSiteTest -->
        <test-method status="FAIL" signature="afterTest()[pri:0, instance:wealthsenseSiteTest.PrivateSiteTest@77caeb3e]" name="afterTest" is-config="true" duration-ms="0" started-at="2016-05-19T16:37:02Z" finished-at="2016-05-19T16:37:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at wealthsenseSiteTest.PrivateSiteTest.afterTest(PrivateSiteTest.java:493)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.afterRun(TestRunner.java:1012)
	at org.testng.TestRunner.run(TestRunner.java:636)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- wealthsenseSiteTest.PrivateSiteTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
